list=[10,20,20,30,40,50]
list.append(15)
print('new list=',list)
list.extend([10,20,30,40])
print('extend list=',list)
list.insert(2,60)
print('inserted list=',list)
list.remove(60)
print('removed list=',list)
list.pop()
print('poped list=',list)
list.pop(3)
print('poped 3rd position=',list)
list.sort()
print('sorted list=',list)
count=list.count(20)
print('no.of 20s in the list=',count)
index=list.index(30)
print('place of 30 in the list=',index)
list.reverse()
print('reverse list=',list)
list.copy()
print('copied list=',list)
list.clear()
print('clear the list=',list)
